import { Router } from "express";
import PostController from "../controllers/PostController";
const PostRoute = Router();
import { VerifyToken } from "../middlewares/jwt";
PostRoute.post("/post", VerifyToken , PostController.create);
PostRoute.put("/post", VerifyToken ,PostController.update);
PostRoute.get("/posts", VerifyToken ,PostController.getAll);
PostRoute.get("/post/:id", VerifyToken ,PostController.getById);
PostRoute.get("/postbyuser/:id", VerifyToken, PostController.getByUserId);
PostRoute.get("/posts/:search", VerifyToken ,PostController.getByTitleOrText);
PostRoute.delete("/post/:postid", VerifyToken, PostController.deleteById);
export default PostRoute;